import groovy.json.JsonSlurper

pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

plugins {
    id 'dev.kikugie.stonecutter' version '0.9.7'
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'AutoConnect'

def autoconnectMetadata = new JsonSlurper().parse(file('gradle/autoconnect-metadata.json'))

include 'unit-tests'
project(':unit-tests').projectDir = file('unit-tests')

stonecutter {
    create(rootProject) {
        versions(autoconnectMetadata.loaders.fabric.targets.collectEntries { minecraftVersion, target ->
            [("fabric-${minecraftVersion}".toString()): minecraftVersion.toString()]
        })
    }
}

autoconnectMetadata.loaders.fabric.targets.keySet().each { minecraftVersion ->
    project(":${"fabric-${minecraftVersion}".toString()}").buildFileName = '../../fabric/fabric.gradle'
}
