modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mixins]]
config="autoconnect.client.mixins.json"

[[mods]]
modId="autoconnect"
version="${version}"
displayName="AutoConnect"
description='''Automatically reconnects to your saved multiplayer server.'''
logoFile="assets/autoconnect/icon.png"
logoBlur=false
authors="m1dLL3"
displayURL="https://github.com/m1dLL3/AutoConnect"

[[dependencies.autoconnect]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.autoconnect]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
